/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as BulkUploadRouteImport } from './routes/bulk-upload'
import { Route as StoriesIdRouteImport } from './routes/stories.$id'
import { Route as StoriesIdEditRouteImport } from './routes/stories.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkUploadRoute = BulkUploadRouteImport.update({
  id: '/bulk-upload',
  path: '/bulk-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIdRoute = StoriesIdRouteImport.update({
  id: '/stories/$id',
  path: '/stories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIdEditRoute = StoriesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StoriesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/bulk-upload': typeof BulkUploadRoute
  '/stories/$id': typeof StoriesIdRouteWithChildren
  '/stories/$id/edit': typeof StoriesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/bulk-upload': typeof BulkUploadRoute
  '/stories/$id': typeof StoriesIdRouteWithChildren
  '/stories/$id/edit': typeof StoriesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/bulk-upload': typeof BulkUploadRoute
  '/stories/$id': typeof StoriesIdRouteWithChildren
  '/stories/$id/edit': typeof StoriesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/add' | '/bulk-upload' | '/stories/$id' | '/stories/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add' | '/bulk-upload' | '/stories/$id' | '/stories/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/bulk-upload'
    | '/stories/$id'
    | '/stories/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  BulkUploadRoute: typeof BulkUploadRoute
  StoriesIdRoute: typeof StoriesIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-upload': {
      id: '/bulk-upload'
      path: '/bulk-upload'
      fullPath: '/bulk-upload'
      preLoaderRoute: typeof BulkUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$id': {
      id: '/stories/$id'
      path: '/stories/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof StoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$id/edit': {
      id: '/stories/$id/edit'
      path: '/edit'
      fullPath: '/stories/$id/edit'
      preLoaderRoute: typeof StoriesIdEditRouteImport
      parentRoute: typeof StoriesIdRoute
    }
  }
}

interface StoriesIdRouteChildren {
  StoriesIdEditRoute: typeof StoriesIdEditRoute
}

const StoriesIdRouteChildren: StoriesIdRouteChildren = {
  StoriesIdEditRoute: StoriesIdEditRoute,
}

const StoriesIdRouteWithChildren = StoriesIdRoute._addFileChildren(
  StoriesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  BulkUploadRoute: BulkUploadRoute,
  StoriesIdRoute: StoriesIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
